---
title: "003_diff_exp"
author: "Me"
date: "06/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Within `Guy11`

### Differential peptide abundance

Perform differential abundance estimation using bootstrap and rank product methods

```{r}
library(pepdiff)
d <- import_data(here::here("cleaned", "cleaned_data.csv"), 
                 gene_id = "molecule_list_name", 
                 treatment = "genotype", 
                 peptide = "peptide_modified_sequence", 
                 seconds = "timepoint")

comparisons <- data.frame(
  control = rep("Guy11", 5),
  c_seconds = rep(0, 5),
  treatment = rep("Guy11", 5),
  t_seconds = c(1,1.5,2,4,6)
)

many <- compare_many(d, comparisons, metrics = c("bootstrap_t", "rank_product"), iters=10000)
many
```


## Plot result heatmaps

```{r,eval=TRUE, fig.height=10, fig.width=10}

lgd <- ComplexHeatmap::Legend(direction = "horizontal",
  col_fun = circlize::colorRamp2(
                           seq(-2, 2, length.out = 11),
                           rev(RColorBrewer::brewer.pal(11, "RdBu"))
                         ),
  title = "Log 2 Fold Change")


plot_heatmap(many, metric = "bootstrap_t", log = TRUE)#,  col_order = col_order)
ComplexHeatmap::draw(lgd, x = grid::unit(8, "in"), y = grid::unit(1, "in"))

plot_heatmap(many, metric = "rank_product", log = TRUE)
ComplexHeatmap::draw(lgd, x = grid::unit(8, "in"), y = grid::unit(1, "in"))
```

```{r, fig.height=10,fig.width=10}
#add colour even when the point isn't significant
plot_heatmap(many, metric = "bootstrap_t", log = TRUE)#,  col_order = col_order, only_sig_points = FALSE)
ComplexHeatmap::draw(lgd, x = grid::unit(8, "in"), y = grid::unit(1, "in"))
```

```{r, fig.width=8}
volcano_plot(many, metric = "bootstrap_t")
```


```{r}
writexl::write_xlsx(many, here::here("analysis","003_differential_abundance_Guy11_w_geno_estimates.xlsx"))
```


## Within `dpmk1`


```{r}
comparisons <- data.frame(
  control = rep("dpmk1", 5),
  c_seconds = rep(0, 5),
  treatment = rep("dpmk1", 5),
  t_seconds = c(1,1.5,2,4,6)
)

many <- compare_many(d, comparisons, metrics = c("bootstrap_t", "rank_product"), iters=10000)
many
```


## Plot result heatmaps

```{r,eval=TRUE, fig.height=10, fig.width=10}

lgd <- ComplexHeatmap::Legend(direction = "horizontal",
  col_fun = circlize::colorRamp2(
                           seq(-2, 2, length.out = 11),
                           rev(RColorBrewer::brewer.pal(11, "RdBu"))
                         ),
  title = "Log 2 Fold Change")


plot_heatmap(many, metric = "bootstrap_t", log = TRUE)#,  col_order = col_order)
ComplexHeatmap::draw(lgd, x = grid::unit(8, "in"), y = grid::unit(1, "in"))

plot_heatmap(many, metric = "rank_product", log = TRUE)
ComplexHeatmap::draw(lgd, x = grid::unit(8, "in"), y = grid::unit(1, "in"))
```

```{r, fig.height=10,fig.width=10}
#add colour even when the point isn't significant
plot_heatmap(many, metric = "bootstrap_t", log = TRUE)#,  col_order = col_order, only_sig_points = FALSE)
ComplexHeatmap::draw(lgd, x = grid::unit(8, "in"), y = grid::unit(1, "in"))
```

```{r, fig.width=8}
volcano_plot(many, metric = "bootstrap_t")
```


```{r}
writexl::write_xlsx(many, here::here("analysis","003_differential_abundance_dpmk_w_geno_estimates.xlsx"))
```